// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace FlightSimulator
{

    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class AirPlaneList
    {
        internal ArrayList nameList;
        internal ArrayList pathList;

        public AirPlaneList(Uri codeBase, String path)
        {
            nameList = new ArrayList();
            pathList = new ArrayList();
            AirPlaneListFile aplf = new AirPlaneListFile(this, codeBase, path);
        }

        public AirPlaneList(String path)
        {
            nameList = new ArrayList();
            pathList = new ArrayList();
            AirPlaneListFile aplf = new AirPlaneListFile(this, path);
        }

        public void Add(String name, String path)
        {
            nameList.Add(name);
            pathList.Add(path);
        }

        public void Print()
        {
            for (int i = 0; i < NItem(); i++)
                System.Console.Out.WriteLine(GetName(i) + " = " + GetPath(i));
        }

        public int NItem()
        {
            return nameList.Count;
        }

        public String GetName(int i)
        {
            return (String)nameList[i];
        }

        public String GetPath(int i)
        {
            return (String)pathList[i];
        }
    }
}
