// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace FlightSimulator
{

    using Jp.Maker1.Io.Textfile;
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class AirPlaneListFile : ReadTextFileOnServer
    {
        internal Uri url;
        internal FileInfo file;

        public AirPlaneListFile(AirPlaneList apl, Uri codeBase, String path)
        {
            //url = null;
            //file = null;
            //try {
            //    url = new Uri(codeBase, path);
            //} catch (Exception e) {
            //    Console.Error.WriteLine(e.StackTrace);
            //}
            //Open(url);
            Open(path);
            ReadAirPlaneListFile(apl, false);
            Close();
        }

        public AirPlaneListFile(AirPlaneList apl, String path)
        {
            url = null;
            file = null;
            try
            {
                file = new FileInfo(path);
            }
            catch (Exception e)
            {
                Console.Error.WriteLine(e.StackTrace);
            }
            Open(file);
            ReadAirPlaneListFile(apl, false);
            Close();
        }

        private void ReadAirPlaneListFile(AirPlaneList apl, bool flagMessage)
        {
            while (true)
            {
                int c = ReadSkipSpace();
                if (c == -1)
                    break;
                if (c == 35)
                {
                    ReadLine();
                }
                else
                {
                    String name = (char)c + DispFormat.Trm(ReadToKugiri("="));
                    String path = DispFormat.Trm(ReadToKugiri(";"));
                    apl.Add(name, path);
                    ReadLine();
                }
            }
        }
    }
}