// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Util.Gui
{


    using System;
    using System.Drawing;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class ClickArea
    {
        public int xo;
        public int yo;
        public int xl;
        public int yl;
        public SolidBrush borderColBrush;
        public SolidBrush colBrush;

        public ClickArea(int xoIn, int yoIn, int xlIn, int ylIn, Color bcolIn, Color colIn)
        {
            SetExtent(xoIn, yoIn, xlIn, ylIn);
            borderColBrush = new SolidBrush(bcolIn);
            colBrush = new SolidBrush(colIn);
        }

        public void SetExtent(int xoIn, int yoIn, int xlIn, int ylIn)
        {
            xo = xoIn;
            yo = yoIn;
            xl = xlIn;
            yl = ylIn;
        }

        public void Draw(Graphics g)
        {
            g.FillRectangle(colBrush, xo, yo, xl, yl);

            g.FillRectangle(borderColBrush, xo, yo, xl, yl);
        }

        public bool Test(int x, int y)
        {
            return (x >= xo) && (x <= xo + xl) && (y >= yo) && (y <= yo + yl);
        }
    }
}