// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Fsim
{

    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class FsimConst
    {
        public static String title = "Flight Simulation Applet";
        public static String author = "Takeshi Saji(Maker-One/Ayahito_404NF)";
        public static String url = "http://www2.odn.ne.jp/~cdh88520/";
    }
}