// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Sim.Tools
{

    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class Function2D
    {
        public double[] x;
        public double[] y;

        public Function2D(double[] xIn, double[] yIn)
        {
            Init(xIn, yIn);
        }

        public void Init(double[] xIn, double[] yIn)
        {
            int n = xIn.Length;
            if (yIn.Length < n)
            {
                n = yIn.Length;
            }
            x = new double[n];
            y = new double[n];
            for (int i = 0; i < n; i++)
            {
                x[i] = xIn[i];
                y[i] = yIn[i];
            }
            if (xIn.Length != yIn.Length)
                System.Console.Out.WriteLine("Œx:Function2D.init():x[]‚Æy[]‚ÌŒÂ”‚ªˆê’v‚µ‚Ä‚¢‚Ü‚¹‚ñ");
        }

        public int GetN()
        {
            return x.Length;
        }

        public double F(double xIn)
        {
            int n = x.Length;

            if (n <= 0)
                return 0.0D;

            if (xIn < x[0])
                return y[0];
            if (xIn >= x[(n - 1)])
                return y[(n - 1)];

            for (int i = 0; i < n - 1; i++)
            {
                if ((xIn >= x[i]) && (xIn < x[(i + 1)]))
                {
                    return y[i] + (y[(i + 1)] - y[i]) * (xIn - x[i]) / (x[(i + 1)] - x[i]);
                }
            }
            return 0.0D;
        }

        public void Print()
        {
            for (int i = 0; i < x.Length; i++)
            {
                System.Console.Out.Write("f(" + x[i] + ")=" + y[i]);
                if (i < x.Length - 1)
                {
                    System.Console.Out.Write(", ");
                }
            }
            System.Console.Out.WriteLine("");
        }

        public double Fo(double xIn)
        {
            int n = x.Length;

            if (n <= 0)
                return 0.0D;

            if (xIn < x[0])
            {
                if (n == 1)
                    return y[0];
                if (x[1] == x[0])
                {
                    return y[0];
                }
                return y[0] + (y[1] - y[0]) * (xIn - x[0]) / (x[1] - x[0]);
            }

            if (xIn >= x[(n - 1)])
            {
                if (n == 1)
                    return y[(n - 1)];
                if (x[(n - 1)] == x[(n - 2)])
                {
                    return y[(n - 1)];
                }
                return y[(n - 2)] + (y[(n - 1)] - y[(n - 2)]) * (xIn - x[(n - 2)]) / (x[(n - 1)] - x[(n - 2)]);
            }

            for (int i = 0; i < n - 1; i++)
            {
                if ((xIn >= x[i]) && (xIn < x[(i + 1)]))
                {
                    return y[i] + (y[(i + 1)] - y[i]) * (xIn - x[i]) / (x[(i + 1)] - x[i]);
                }
            }
            return 0.0D;
        }
    }
}