// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace FlightSimulator
{

    using Jp.Maker1.Sim.Tools;
    using Jp.Maker1.Vsys3.Tools;
    using System;
    using System.Drawing;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class GraphicsGenerator
    {
        public const int CAPTION_X = 270;
        public const int CAPTION_Y = 180;
        public static readonly Color CAPTION_COLOR = Color.White;
        public static readonly Font CAPTION_FONT = new Font("SansSerif", 16);
        public const double CAPTION_TIME_LONG = 4.0D;
        public const double CAPTION_TIME_MIDDLE = 3.0D;
        public const double CAPTION_TIME_SHORT = 2.0D;
        public Projector proj;
        private Clipper clip;
        private Scine sc;
        private OpticalAmbience oa;
        private VsPolygon earth;
        private VsObject glid1m;
        private VsObject glid10m;
        private VsObject glid100m;
        private VsObject glid1km;
        private VsObject glid10km;
        private VsPolygon runway;
        private VsObject glid_runway;
        private Color bgColor;
        private int earthColorRed;
        private int earthColorGreen;
        private int earthColorBlue;
        private Color glid1mColor;
        private Color glid10mColor;
        private Color glid100mColor;
        private Color glid1kmColor;
        private Color glid10kmColor;
        private int runwayColorRed;
        private int runwayColorGreen;
        private int runwayColorBlue;
        private Color gridRunwayColor;

        //public Color interfaceColor;
        public Pen interfaceColorPen;
        public SolidBrush interfaceColorBrush;

        //public Color interfaceColorD;
        public Pen interfaceColorDPen;

        public Color instrumentColor;
        public Color instrumentGreen;
        public Color instrumentYellow;
        public Color instrumentRed;
        public Color informationColor;
        public Color simInterfaceColor;
        public Color padLockColor;

        public Font stdFont;
        public Font bigFont;
        public Font smallFont;
        public Font padFont;

        public int stick_center_x;
        public int stick_center_y;
        public int stick_x_width;
        public int stick_y_width;
        private int rudder_center_x;
        private int rudder_center_y;
        private int rudder_x_witdh;
        private int rudder_y_width;
        private int throttle_x;
        private int throttle_y;
        private int throttle_width;
        private int mixture_x;
        private int mixture_y;
        private int mixture_width;
        private int prop_pitch_x;
        private int prop_pitch_y;
        private int prop_pitch_width;
        private int brake_right_x;
        private int brake_right_y;
        private int brake_right_width;
        private int brake_left_x;
        private int brake_left_y;
        private int brake_left_width;

        private VsObjectList instrument_object_list;
        private VsObject pitch_miniature_aircraft;
        private VsObject roll_miniature_aircraft;
        private VsObject heading_miniature_aircraft;
        private VsObject velocity_vector;
        private VsObject artificial_horizon;
        private VsObject front_point;
        private int v_true_x;
        private int v_true_y;

        private int alt_x;
        private int alt_y;

        private int atmo_x;
        private int atmo_y;

        private int gear_x;
        private int gear_y;
        private int gear_box_size;
        private int gear_box_maegine;

        private int flap_x;
        private int flap_y;
        private int flap_width;

        private int stallAlert_x;
        private int stallAlert_y;

        private int pause_x;
        private int pause_y;
        private int slowMoton_x;
        private int slowMoton_y;

        public GraphicsGenerator(Uri codeBase, double sX0, double sY0, double sX1, double sY1)
        {
            sc = new Scine();
            oa = new OpticalAmbience();
            bgColor = Color.FromArgb(134, 171, 225);
            earthColorRed = 50;
            earthColorGreen = 93;
            earthColorBlue = 45;
            glid1mColor = Color.FromArgb(55, 102, 48);
            glid10mColor = Color.FromArgb(61, 113, 59);
            glid100mColor = Color.FromArgb(67, 124, 65);
            glid1kmColor = Color.FromArgb(61, 113, 59);
            glid10kmColor = Color.FromArgb(55, 102, 48);
            runwayColorRed = 151;
            runwayColorGreen = 151;
            runwayColorBlue = 159;
            gridRunwayColor = Color.FromArgb(160, 160, 170);
            interfaceColorPen = new Pen(Color.FromArgb(200, 200, 255));
            interfaceColorBrush = new SolidBrush(Color.FromArgb(200, 200, 255));
            interfaceColorDPen = new Pen(Color.FromArgb(180, 180, 235));
            instrumentColor = Color.FromArgb(255, 255, 255);
            instrumentGreen = Color.FromArgb(128, 200, 128);
            instrumentYellow = Color.FromArgb(200, 200, 128);
            instrumentRed = Color.FromArgb(200, 128, 128);
            informationColor = Color.FromArgb(220, 220, 255);
            simInterfaceColor = Color.FromArgb(230, 255, 200);
            padLockColor = Color.FromArgb(200, 200, 255);
            stdFont = new Font("SansSelif", 12);
            bigFont = new Font("SansSelif", 16);
            smallFont = new Font("SansSelif", 9);
            padFont = new Font("SansSelif", 11);
            stick_center_x = 300;
            stick_center_y = 200;
            stick_x_width = 140;
            stick_y_width = 140;
            rudder_center_x = 300;
            rudder_center_y = 320;
            rudder_x_witdh = 45;
            rudder_y_width = 30;
            throttle_x = 10;
            throttle_y = 390;
            throttle_width = 100;
            mixture_x = 25;
            mixture_y = 390;
            mixture_width = 100;
            prop_pitch_x = 40;
            prop_pitch_y = 390;
            prop_pitch_width = 100;
            brake_right_x = 580;
            brake_right_y = 390;
            brake_right_width = 100;
            brake_left_x = 565;
            brake_left_y = 390;
            brake_left_width = 100;
            instrument_object_list = new VsObjectList();
            v_true_x = 100;
            v_true_y = 12;
            alt_x = 185;
            alt_y = 12;
            atmo_x = 280;
            atmo_y = 12;
            gear_x = 130;
            gear_y = 325;
            gear_box_size = 9;
            gear_box_maegine = 12;
            flap_x = 450;
            flap_y = 395;
            flap_width = 100;
            stallAlert_x = 257;
            stallAlert_y = 140;
            pause_x = 275;
            pause_y = 100;
            slowMoton_x = 245;
            slowMoton_y = 115;
            proj = new Projector(sX1 - sX0 + 1.0D, sY1 - sY0 + 1.0D, MathTool.DegToRad(45.0D));
            proj.SetVerticalParamer(0.0D, 0.0D, sX1 - sX0 + 1.0D, sY1 - sY0 + 1.0D, MathTool.DegToRad(45.0D));
            clip = new Clipper(sX0, sY0, sX1, sY1);

            Matrix44 mtemp = new Matrix44();
            Matrix44 smat = new Matrix44();
            mtemp.SetRxMat(MathTool.DegToRad(90.0D));
            earth = ((VsPolygon)Jp.Maker1.Vsys3.Tools.BasicObject.RegularPolygon(32, earthColorRed, earthColorGreen, earthColorBlue).Transform(mtemp));

            glid10km = Jp.Maker1.Vsys3.Tools.BasicObject.XzGlid(0.0D, -50000.0D, -50000.0D, 50000.0D, 50000.0D, 10000.0D, 10000.0D, glid10kmColor);
            glid1km = Jp.Maker1.Vsys3.Tools.BasicObject.XzGlid(0.0D, -10000.0D, -10000.0D, 10000.0D, 10000.0D, 1000.0D, 1000.0D, glid1kmColor);
            glid100m = Jp.Maker1.Vsys3.Tools.BasicObject.XzGlid(0.0D, -1000.0D, -1000.0D, 1000.0D, 1000.0D, 100.0D, 100.0D, glid100mColor);
            glid10m = Jp.Maker1.Vsys3.Tools.BasicObject.XzGlid(0.0D, -200.0D, -200.0D, 200.0D, 200.0D, 10.0D, 10.0D, glid10mColor);
            glid1m = Jp.Maker1.Vsys3.Tools.BasicObject.XzGlid(0.0D, -30.0D, -30.0D, 30.0D, 30.0D, 1.0D, 1.0D, glid1mColor);

            smat.SetSMat(60.0D, 0.0D, 1000.0D);
            runway = ((VsPolygon)Jp.Maker1.Vsys3.Tools.BasicObject.Square(runwayColorRed, runwayColorGreen, runwayColorBlue).Transform(mtemp.MultMat(smat)));
            glid_runway = Jp.Maker1.Vsys3.Tools.BasicObject.XzGlid(0.1D, -30.0D, -500.0D, 30.0D, 500.0D, 10.0D, 10.0D, gridRunwayColor);

            FormUnitFile fmu = new FormUnitFile(instrument_object_list, codeBase, "data/instrument.fmu", "data/instrument.mdf");

            pitch_miniature_aircraft = instrument_object_list.Get("PITCH_MINIATURE_ARECRAFT");
            pitch_miniature_aircraft.SetColor(informationColor);
            roll_miniature_aircraft = instrument_object_list.Get("ROLL_MINIATURE_ARECRAFT");
            roll_miniature_aircraft.SetColor(informationColor);
            heading_miniature_aircraft = instrument_object_list.Get("HEADING_MINIATURE_ARECRAFT");
            heading_miniature_aircraft.SetColor(instrumentColor);
            velocity_vector = instrument_object_list.Get("VELOCITY_VECTOR");
            velocity_vector.SetColor(informationColor);
            artificial_horizon = instrument_object_list.Get("ARTIFICIAL_HORIZON");
            artificial_horizon.SetColor(instrumentColor);
            front_point = instrument_object_list.Get("FRONT_POINT");
            front_point.SetColor(informationColor);
        }

        public void CreateImage(Graphics g, AirPlane ap, SimulatorInterface simif, double dt)
        {
            CreateView(g, ap.pMotion.wpos, ap.pMotion.wom.MultMat(ap.plane.opm).MultMat(ap.pilot.ViewMatrix()));

            DrawPadLock(g, ap);

            DrawInterfase(g, ap);

            DrawInstrument(g, ap, simif, dt);

            if (simif.dispDynamicsSw == 1)
            {
                DrawDynamics(g, ap, dt);
            }

            DrawSimInterfase(g, simif);

            // g.SetFont(stdFont);
        }

        public void CreateView(Graphics g, Vector3D pos, Matrix44 wem)
        {
            Scine scn = new Scine();
            scn.optamb = oa;
            scn.Add(MakeEarth(pos).Transform(wem));
            Scine view = scn.MakeView(clip, proj, false);

            // g.SetColor(bgColor);
            //g.FillRect((int)clip.vp_xmin, (int)clip.vp_ymin, (int)(clip.vp_xmax - clip.vp_xmin + 1.0D), (int)(clip.vp_ymax - clip.vp_ymin + 1.0D));
            g.FillRectangle(new SolidBrush(bgColor), (int)clip.vp_xmin, (int)clip.vp_ymin, (int)(clip.vp_xmax - clip.vp_xmin + 1.0D), (int)(clip.vp_ymax - clip.vp_ymin + 1.0D));
            view.Draw(g);
        }

        public VsObject MakeEarth(Vector3D pos)
        {
            VsObject ret = new VsObject();

            Matrix44 smat = new Matrix44();
            Matrix44 mtemp = new Matrix44();

            double r = 6370000.0D;

            double x = pos.x;
            double y = pos.y;
            double z = pos.z;

            double h = Math.Abs(y);
            double scale;
            if (h != 0.0D)
                scale = 2.0D * h * r / Math.Sqrt(h * h + 2.0D * h * r);
            else
            {
                scale = 1.0D;
            }
            smat.SetSMat(scale, scale, scale);
            mtemp.SetTMat(x, 0.0D, z);
            ret.Add(earth.Transform(smat).Transform(mtemp));

            if (y > 2300.0D)
            {
                scale = 10000.0D;
                double tx = x - (x / scale - Math.Floor(x / scale)) * scale;
                double tz = z - (z / scale - Math.Floor(z / scale)) * scale;
                mtemp.SetTMat(tx, 0.0D, tz);
                ret.Add(glid10km.Transform(mtemp));
            }
            scale = 1000.0D;
            double tx_0 = x - (x / scale - Math.Floor(x / scale)) * scale;
            double tz_1 = z - (z / scale - Math.Floor(z / scale)) * scale;
            mtemp.SetTMat(tx_0, 0.0D, tz_1);
            ret.Add(glid1km.Transform(mtemp));

            if (y < 2700.0D)
            {
                scale = 100.0D;
                tx_0 = x - (x / scale - Math.Floor(x / scale)) * scale;
                tz_1 = z - (z / scale - Math.Floor(z / scale)) * scale;
                mtemp.SetTMat(tx_0, 0.0D, tz_1);
                ret.Add(glid100m.Transform(mtemp));
            }
            if (y < 270.0D)
            {
                scale = 10.0D;
                tx_0 = x - (x / scale - Math.Floor(x / scale)) * scale;
                tz_1 = z - (z / scale - Math.Floor(z / scale)) * scale;
                mtemp.SetTMat(tx_0, 0.0D, tz_1);
                ret.Add(glid10m.Transform(mtemp));
            }

            ret.Add(runway);
            if (y < 270.0D)
            {
                ret.Add(glid_runway);
            }

            return ret;
        }

        public void DrawInterfase(Graphics g, AirPlane ap)
        {
            CockpitInterface cif = ap.cif;

            //g.SetColor(interfaceColor);
            // g.SetFont(stdFont);

            double elevcent = ap.elevator[0, 0].delta_max / (ap.elevator[0, 0].delta_max - ap.elevator[0, 0].delta_min);
            int stx = stick_center_x;
            int sty = stick_center_y - stick_y_width + (int)(stick_y_width * 2.0D * elevcent + 0.5D);

            // g.SetColor(interfaceColorD);
            //g.DrawLine(stx, sty - 7, stx, sty + 7);
            //g.DrawLine(stx - 7, sty, stx + 7, sty);

            g.DrawLine(interfaceColorDPen, stx, sty - 7, stx, sty + 7);
            g.DrawLine(interfaceColorDPen, stx - 7, sty, stx + 7, sty);

            //g.SetColor(interfaceColor);
            //g.DrawRect(stick_center_x - stick_x_width, stick_center_y - stick_y_width, stick_x_width * 2, stick_y_width * 2);

            g.DrawRectangle(interfaceColorPen, stick_center_x - stick_x_width, stick_center_y - stick_y_width, stick_x_width * 2, stick_y_width * 2);

            int x = (int)(cif.stick_pos_x * stick_x_width + 0.5D) + stick_center_x;
            int y = (int)(cif.stick_pos_y * stick_y_width + 0.5D) + stick_center_y;
            g.DrawLine(interfaceColorPen,x, y, stx, sty);
            //g.FillOval(x - 3, y - 3, 6, 6);

            g.FillEllipse(interfaceColorBrush, x - 3, y - 3, 6, 6);


            if (cif.stick_mode == 0)
            {
                g.DrawString("CLICK TO ACTIVATE STICK", stdFont, interfaceColorBrush, stick_center_x - 70, stick_center_y - stick_y_width + 12);
                g.DrawEllipse(interfaceColorPen,x - 5, y - 5, 10, 10);
            }
            else
            {
                g.DrawLine(interfaceColorPen, x - 7, y, x + 7, y);
                g.DrawLine(interfaceColorPen, x, y + 7, x, y - 7);
            }

            int x0 = rudder_center_x - rudder_x_witdh;
            int x1 = rudder_center_x + rudder_x_witdh;
            int y0 = rudder_center_y + (int)(rudder_y_width * cif.rudder_pos + 0.5D);
            int y1 = rudder_center_y - (int)(rudder_y_width * cif.rudder_pos + 0.5D);

            // g.SetColor(interfaceColorD);
            //  g.DrawRect(x0 - 5, y0 - 5, 10, 10);
            // g.DrawRect(x1 - 5, y1 - 5, 10, 11);
            // g.DrawLine(x0, y0, x1, y1);

            y0 = rudder_center_y + (int)(rudder_y_width * cif.frudder_pos.output + 0.5D);
            y1 = rudder_center_y - (int)(rudder_y_width * cif.frudder_pos.output + 0.5D);
            //g.SetColor(interfaceColor);
            //g.DrawRect(x0 - 5, y0 - 5, 10, 10);
            //g.DrawRect(x1 - 5, y1 - 5, 10, 11);
            //g.DrawLine(x0, y0, x1, y1);

            x0 = throttle_x;
            y0 = throttle_y;
            double pos;
            for (pos = 0.1D; pos <= 0.9D; pos += 0.1D)
            {
                y = (int)(throttle_width * pos + 0.5D);
                //     g.DrawLine(x0, y0 - y, x0 + 2, y0 - y);
            }
            y = (int)(throttle_width * 0.5D + 0.5D);
            //    g.DrawLine(x0, y0 - y, x0 + 5, y0 - y);
            //  g.DrawString("T", x0 + 2, y0 - throttle_width - 1);
            //g.DrawRect(x0, y0 - throttle_width, 10, throttle_width);
            y = (int)(throttle_width * cif.throttle_pos + 0.5D);
            //    g.FillRect(x0 + 2, y0 - y, 7, y);
            //g.DrawString(Jp.Maker1.Util.DispFormat.DoubleFormat(cif.throttle_pos * 100.0D, 0) + "%", x0, y0 - throttle_width - 13);

            x0 = mixture_x;
            y0 = mixture_y;
            for (pos = 0.1D; pos <= 0.9D; pos += 0.1D)
            {
                y = (int)(throttle_width * pos + 0.5D);
                //g.DrawLine(x0, y0 - y, x0 + 2, y0 - y);
            }
            y = (int)(throttle_width * 0.5D + 0.5D);
            // g.DrawLine(x0, y0 - y, x0 + 5, y0 - y);
            // g.DrawString("M", x0 + 1, y0 - throttle_width - 1);
            // g.DrawRect(x0, y0 - mixture_width, 10, mixture_width);
            y = (int)(mixture_width * cif.mixture_pos + 0.5D);
            // g.FillRect(x0 + 2, y0 - y, 7, y);

            x0 = prop_pitch_x;
            y0 = prop_pitch_y;
            for (pos = 0.1D; pos <= 0.9D; pos += 0.1D)
            {
                y = (int)(throttle_width * pos + 0.5D);
                // g.DrawLine(x0, y0 - y, x0 + 2, y0 - y);
            }
            y = (int)(throttle_width * 0.5D + 0.5D);
            //   g.DrawLine(x0, y0 - y, x0 + 5, y0 - y);
            //  g.DrawString("P", x0 + 2, y0 - throttle_width - 1);
            //  g.DrawRect(x0, y0 - prop_pitch_width, 10, prop_pitch_width);
            y = (int)(prop_pitch_width * cif.prop_pitch_pos + 0.5D);
            //  g.FillRect(x0 + 2, y0 - y, 7, y);

            x0 = brake_right_x;
            y0 = brake_right_y;
            for (pos = 0.1D; pos <= 0.9D; pos += 0.1D)
            {
                y = (int)(throttle_width * pos + 0.5D);
                //g.DrawLine(x0, y0 - y, x0 + 2, y0 - y);
            }
            // g.DrawString("R", x0 + 2, y0 - throttle_width - 1);
            y = (int)(throttle_width * 0.5D + 0.5D);
            // g.DrawLine(x0, y0 - y, x0 + 5, y0 - y);
            // g.DrawRect(x0, y0 - brake_right_width, 10, brake_right_width);
            y = (int)(brake_right_width * cif.brakeRight_pos + 0.5D);
            // g.FillRect(x0 + 2, y0 - y, 7, y);

            x0 = brake_left_x;
            y0 = brake_left_y;
            for (pos = 0.1D; pos <= 0.9D; pos += 0.1D)
            {
                y = (int)(throttle_width * pos + 0.5D);
                //  g.DrawLine(x0, y0 - y, x0 + 2, y0 - y);
            }
            //g.DrawString("W.BRK", x0 - 2, y0 - throttle_width - 13);
            //  g.DrawString("L", x0 + 2, y0 - throttle_width - 1);
            y = (int)(throttle_width * 0.5D + 0.5D);
            //  g.DrawLine(x0, y0 - y, x0 + 5, y0 - y);
            //  g.DrawRect(x0, y0 - brake_left_width, 10, brake_left_width);
            y = (int)(brake_left_width * cif.brakeLeft_pos + 0.5D);
            // g.FillRect(x0 + 2, y0 - y, 7, y);
        }

        public void DrawPadLock(Graphics g, AirPlane ap)
        {
            double r = 110.0D;
            double l = 20.0D;

            //g.SetColor(padLockColor);
            // g.SetFont(padFont);
            PadlockObject pobj = ap.pilot.pObjList.PadlockObj(ap);
            if (pobj != null)
            {
                Vector3D vec = pobj.RPosPilotView(ap);
                Vector3D vec2 = clip.Vs_point_clip_3df(vec);
                if (vec2 != null)
                {
                    vec2 = proj.Project(vec2);
                    vec2 = clip.Vs_point_clip2d(vec2);
                }
                if (vec2 != null)
                {
                    int x0 = (int)(vec2.x + 0.5D);
                    int y0 = (int)(vec2.y + 0.5D);
                    g.DrawRectangle(new Pen(padLockColor), x0 - 10, y0 - 10, 1, 1);
                    //g.DrawRect(x0 + 8, y0 - 10, 1, 1);
                    //g.DrawRect(x0 + 8, y0 + 8, 1, 1);
                    //g.DrawRect(x0 - 10, y0 + 8, 1, 1);
                    //g.DrawString(pobj.name, x0 + 12, y0 + 9);
                }
                else
                {
                    Bearing3 be3 = pobj.Bearing2PilotView(ap);
                    double sinr = -System.Math.Sin(be3.roll.GetValue());
                    double cosr = -System.Math.Cos(be3.roll.GetValue());
                    double w = l * System.Math.Sin(be3.pitch.GetValue() / 2.0D);
                    double h = l * System.Math.Cos(be3.pitch.GetValue() / 2.0D);
                    int x0_0 = 300 + (int)(r * sinr);
                    int y0_1 = 200 + (int)(r * cosr);
                    int x1 = 300 + (int)((r + l) * sinr);
                    int y1 = 200 + (int)((r + l) * cosr);
                    Jp.Maker1.Util.Symbol.DrawArrow(g, x0_0, y0_1, x1, y1, (int)h, (int)w);
                    //g.DrawString(pobj.name, (x0_0 + x1) / 2 + (int)(l * 0.71D), (y0_1 + y1) / 2 + (int)(l * 0.71D));
                    g.DrawString(pobj.name, padFont, new SolidBrush(padLockColor), (x0_0 + x1) / 2 + (int)(l * 0.71D), (y0_1 + y1) / 2 + (int)(l * 0.71D));
                }
            }
        }

        public void DrawInstrument(Graphics g, AirPlane ap, SimulatorInterface simif, double dt)
        {
            Matrix44 tmat = new Matrix44();
            Matrix44 smat = new Matrix44();
            Matrix44 rmat = new Matrix44();
            Matrix44 rzmat = new Matrix44();
            Matrix44 rxmat = new Matrix44();
            Matrix44 mat = new Matrix44();
            Scine scine = new Scine();

            //g.SetColor(informationColor);
            //g.SetFont(stdFont);

            SolidBrush informationBrush = new SolidBrush(informationColor);
            Pen informationPen = new Pen(informationColor);
            g.DrawString(ap.plane.name, stdFont, informationBrush, 300 - ap.plane.name.Length * 3, 365);

            if (simif.dispInformationSw == 1)
            {
                double x = ap.pMotion.ov.Length();
                //g.DrawString("V: " + Jp.Maker1.Util.DispFormat.DoubleFormat(x, 3, 1) + " m/s", v_true_x, v_true_y);
                //g.DrawString("V: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Sim.Tools.UnitConvert.Mps2kmph(x), 3, 1) + " km/h", v_true_x, v_true_y + 12);
                //g.DrawString("V: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Sim.Tools.UnitConvert.Mps2kt(x), 3, 1) + " kt", v_true_x, v_true_y + 24);

                x = ap.pMotion.wpos.y;
                //g.DrawString("ALT: " + Jp.Maker1.Util.DispFormat.DoubleFormat(x, 5, 1) + " m", alt_x, alt_y);
                //g.DrawString("ALT: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Sim.Tools.UnitConvert.M2ft(x), 5, 1) + " ft", alt_x, alt_y + 12);
            }

            double pitch = ap.pMotion.pitch.GetValue();
            double roll = ap.pMotion.roll.GetValue();
            g.DrawString("PIT: " + DispFormat.DoubleFormat(MathTool.RadToDeg(pitch), 5, 1) + " deg", stdFont, informationBrush, 515, 12);
            g.DrawString("ROL: " + DispFormat.DoubleFormat(MathTool.RadToDeg(roll), 5, 1) + " deg", stdFont, informationBrush, 512, 89);
            tmat.SetTMat(550.0D, 45.0D, 0.0D);
            smat.SetSMat(30.0D, -30.0D, 0.0D);
            if ((roll > 1.570796326794897D) || (roll < -1.570796326794897D))
                rmat.SetRzMat(Math.PI - pitch);
            else
            {
                rmat.SetRzMat(pitch);
            }
            mat = smat.MultMat(rmat).MultMat(tmat);
            scine.Add(pitch_miniature_aircraft.Transform(mat));
            g.DrawEllipse(informationPen, 520, 15, 60, 60);
            tmat.SetTMat(550.0D, 121.0D, 0.0D);
            smat.SetSMat(30.0D, -30.0D, 0.0D);
            rmat.SetRzMat(-roll);
            mat = smat.MultMat(rmat).MultMat(tmat);
            scine.Add(roll_miniature_aircraft.Transform(mat));
            g.DrawEllipse(informationPen, 520, 91, 60, 60);

            if (simif.dispInformationSw == 1)
            {
                double x_0 = ap.atmos.h;
                //g.DrawString("H': " + Jp.Maker1.Util.DispFormat.DoubleFormat(x_0, 5, 1) + " m'", atmo_x, atmo_y);
                x_0 = ap.atmos.tc;
                //g.DrawString("t: " + Jp.Maker1.Util.DispFormat.DoubleFormat(x_0, 4, 1) + " Ž", atmo_x, atmo_y + 12);
                x_0 = ap.atmos.t;
                //g.DrawString("T: " + Jp.Maker1.Util.DispFormat.DoubleFormat(x_0, 4, 1) + " K", atmo_x, atmo_y + 24);
                x_0 = ap.atmos.p;
                //g.DrawString("p: " + Jp.Maker1.Util.DispFormat.DoubleFormat(x_0 / 100.0D, 4, 1) + " hPa", atmo_x + 90, atmo_y);
                x_0 = ap.atmos.rho;
                //g.DrawString("ƒÏ: " + Jp.Maker1.Util.DispFormat.DoubleFormat(x_0, 1, 3) + " kg/m3", atmo_x + 90, atmo_y + 12);
                x_0 = ap.atmos.a;
                // g.DrawString("a: " + Jp.Maker1.Util.DispFormat.DoubleFormat(x_0, 3, 1) + " m/sec", atmo_x + 90, atmo_y + 24);
            }

            double alpha = ap.pMotion.alpha;
            double beta = ap.pMotion.beta;
            if (simif.dispInformationSw == 1)
            {
                //g.DrawString("ƒ¿: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Util.MathTool.RadToDeg(alpha), 3, 1) + " deg", 2, 60);
                // g.DrawString("ƒÀ: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Util.MathTool.RadToDeg(beta), 3, 1) + " deg", 2, 72);
            }

            Vector3D vec = ap.pMotion.ov.SclProd(60000000.0D).MultMat(ap.pilot.ViewMatrix());
            if ((vec != null) && (vec.z > 0.0D))
            {
                vec = proj.Project(vec);
                tmat.SetTMat(vec.x, vec.y, vec.z);
                scine.Add(velocity_vector.Transform(tmat));
            }

            vec.SetVec(0.0D, 0.0D, 60000000.0D);
            vec = vec.MultMat(ap.pilot.ViewMatrix());
            if ((vec != null) && (vec.z > 0.0D))
            {
                vec = proj.Project(vec);
                tmat.SetTMat(vec.x, vec.y, vec.z);
                scine.Add(front_point.Transform(tmat));
            }

            vec = ap.pMotion.force.R2l().SclProd(-1.0D / ap.inp.m);
            vec.z = 0.0D;
            double x_1 = vec.Length();
            Vector3D vec2 = vec.NmlVec().SclProd(50.0D);
            vec = vec.NmlVec().SclProd(100.0D);
            Vector3D vec3 = vec.NmlVec().SclProd(113.0D);
            Jp.Maker1.Util.Symbol.DrawArrow(g, 300 + (int)vec2.x, 200 - (int)vec2.y, 300 + (int)vec.x, 200 - (int)vec.y, 50.0D, x_1 * 4.0D);
            //g.DrawString(Jp.Maker1.Util.DispFormat.DoubleFormat(x_1 / 9.80655D, 2) + "G", 286 + (int)vec3.x, 200 - (int)vec3.y);

            vec = ap.pMotion.force.R2l().SclProd(-1.0D / ap.inp.m);
            x_1 = vec.z;
            //  g.DrawString(Jp.Maker1.Util.DispFormat.DoubleFormat(x_1 / 9.80655D, 2) + "G", 120, 192);
            if (Math.Abs((int)(x_1 * 10.0D)) >= 1)
            {
                Jp.Maker1.Util.Symbol.DrawArrow(g, 150, 200, 150 + (int)(x_1 * 10.0D), 200, (int)(Math.Abs(x_1) * 10.0D), 10.0D);
                Jp.Maker1.Util.Symbol.DrawArrow(g, 450, 200, 450 - (int)(x_1 * 10.0D), 200, (int)(Math.Abs(x_1) * 10.0D), 10.0D);
            }

            int xx = 2;
            int yy = 100;
            vec = ap.pMotion.force.SclProd(-1.0D / ap.inp.m / 9.80655D);
            if (simif.dispInformationSw == 1)
            {
                //g.DrawString("Gx: " + Jp.Maker1.Util.DispFormat.DoubleFormat(vec.x, 2, 4) + " [G]", xx, yy);
                yy += 11;
                // g.DrawString("Gy: " + Jp.Maker1.Util.DispFormat.DoubleFormat(vec.y, 2, 4) + " [G]", xx, yy);
                yy += 11;
                //g.DrawString("Gz: " + Jp.Maker1.Util.DispFormat.DoubleFormat(vec.z, 2, 4) + " [G]", xx, yy);
                yy += 11;
            }

            if (ap.max_k_stall_wing > 1.0D)
            {
                //g.DrawString("STALL", stallAlert_x + 25, stallAlert_y);
            }
            else if (ap.max_k_stall_wing > 0.95D)
            {
                //g.DrawString("STALL WARNING", stallAlert_x, stallAlert_y);
            }

            //g.SetColor(instrumentColor);

            double yaw = ap.pMotion.yaw.GetValue();
            //g.DrawString("HDG: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Util.MathTool.RadToDeg(yaw), 5, 1) + " deg", 512, 165);
            tmat.SetTMat(550.0D, 197.0D, 0.0D);
            smat.SetSMat(30.0D, 30.0D, 0.0D);
            rmat.SetRzMat(yaw);
            mat = smat.MultMat(rmat).MultMat(tmat);
            scine.Add(heading_miniature_aircraft.Transform(mat));
            // g.DrawOval(520, 167, 60, 60);

            rzmat.SetRzMat(-ap.pMotion.roll.GetValue());
            rxmat.SetRxMat(-ap.pMotion.pitch.GetValue());
            mat = rxmat.MultMat(rzmat);
            Scine scine2 = new Scine();
            scine2.Add(artificial_horizon.Transform(mat.MultMat(ap.pilot.ViewMatrix())));
            Scine view = new Scine();
            view = scine2.MakeView(clip, proj, false);
            view.Draw(g);

            // g.SetFont(bigFont);
            x_1 = ap.pMotion.vc.Length() * Math.Sqrt(ap.atmos.rho / 1.225D);
            // g.DrawString("ASI: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Sim.Tools.UnitConvert.Mps2kt(x_1), 3, 0) + " kt", 190, 380);

            x_1 = ap.pMotion.wpos.y;
            //g.DrawString("ALT: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Sim.Tools.UnitConvert.M2ft(x_1), 5, 0) + " ft", 190, 396);

            x_1 = ap.pMotion.wv.y;
            //g.DrawString("VSI: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Sim.Tools.UnitConvert.M2ft(x_1) * 60.0D, 5, 0) + " fpm", 305, 380);

            x_1 = ap.pMotion.omega.z;
            //           g.DrawString("YRT: " + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Util.MathTool.RadToDeg(x_1) * 60.0D, 3, 0) + " deg/m", 305, 396);

            for (int i = 0; i < ap.n_LandingGear; i++)
            {
                if (ap.landing_gear[i, 1].flag == 1)
                    xx = gear_x;
                else
                {
                    xx = gear_x - gear_box_maegine / 2;
                }
                yy = gear_y + i * gear_box_maegine * 3;
                for (int lr = 0; lr <= 1; lr++)
                {
                    if (ap.landing_gear[i, lr].flag == 1)
                    {
                        int xx1;

                        if (lr == 0)
                            xx1 = xx + gear_box_maegine;
                        else
                        {
                            xx1 = xx;
                        }
                        x_1 = ap.landing_gear[i, lr].delta;
                        if (x_1 == 0.0D)
                        {
                            //g.SetColor(instrumentRed);
                            //g.FillRect(xx1 + 2, yy + 2, gear_box_size - 3, gear_box_size - 3);
                        }
                        else if (x_1 == 1.0D)
                        {
                            //g.SetColor(instrumentGreen);
                            //g.FillRect(xx1 + 2, yy + 2 + gear_box_maegine * 2, gear_box_size - 3, gear_box_size - 3);
                        }
                        else
                        {
                            // g.SetColor(instrumentYellow);
                            // g.FillRect(xx1 + 2, yy + 2 + gear_box_maegine, gear_box_size - 3, gear_box_size - 3);
                        }
                        //g.SetColor(instrumentColor);
                        //g.DrawRect(xx1, yy, gear_box_size, gear_box_size);
                        //g.DrawRect(xx1, yy + gear_box_maegine, gear_box_size, gear_box_size);
                        //g.DrawRect(xx1, yy + gear_box_maegine * 2, gear_box_size, gear_box_size);
                    }
                }

            }

            //g.SetFont(smallFont);
            ControlPlane flap = ap.t_flap[0, 0];
            if (ap.t_flap[0, 0].type != 0)
            {
                xx = flap_x;
                yy = flap_y;
                // g.DrawRect(xx, yy - flap_width, 10, flap_width);
                for (double ang = 0.0D; ang < MathTool.RadToDeg(flap.delta_max) + 0.1D; ang += 10.0D)
                {
                    x_1 = (MathTool.DegToRad(ang) - flap.delta_min) / (flap.delta_max - flap.delta_min);
                    int yy1 = yy - flap_width + (int)(flap_width * x_1 + 0.5D);
                    // g.DrawLine(xx + 10, yy1, xx + 13, yy1);
                    // g.DrawString("" + (int)ang, xx + 14, yy1);
                }
                x_1 = (flap.delta - flap.delta_min) / (flap.delta_max - flap.delta_min);
                int yy1_2 = (int)(flap_width * x_1 + 0.5D);
                // g.FillRect(xx + 2, yy - flap_width, 7, yy1_2);
            }
            //g.SetFont(stdFont);

            scine.Draw(g);
            //g.SetFont(stdFont);
        }

        public void DrawDynamics(Graphics g, AirPlane ap, double dt)
        {
            DrawArrangement dr = new DrawArrangement();

            Vector3D vec = new Vector3D();

            //g.SetFont(new Font("Sansserif", 11));
            //g.DrawString("ƒÃbase[deg]:" + Jp.Maker1.Util.DispFormat.DoubleFormat(ap.interference.wf_epsilon / Math.PI * 180.0D, 2), 200, 88);
            //g.DrawString("ƒÃ[deg]:" + Jp.Maker1.Util.DispFormat.DoubleFormat(ap.interference.wf_epsilon_htail / Math.PI * 180.0D, 2), 200, 100);
            //g.DrawString("CL:" + DispFormat.DoubleFormat(ap.interference.wing_cl, 2), 200, 76);
            //g.DrawString("AR:" + DispFormat.DoubleFormat(ap.interference.wing_ar, 2), 200, 64);

            //g.DrawString("WG K_STALL:" + Jp.Maker1.Util.DispFormat.DoubleFormat(ap.max_k_stall_wing, 2), 400, 64);
            //g.DrawString("HT K_STALL:" + Jp.Maker1.Util.DispFormat.DoubleFormat(ap.max_k_stall_htail, 2), 400, 76);

            int xx = 220;
            int y = 240;
            //g.SetFont(new Font("Sansserif", 0, 11));
            int lr;
            for (lr = 0; lr < 2; lr++)
            {
                if (ap.elevator[0, lr].type != 0)
                {
                    //      g.DrawString("ƒÂe" + Jp.Maker1.Fsim.AirPlane.lrName[lr] + ":" + Jp.Maker1.Util.DispFormat.DoubleFormat(Jp.Maker1.Util.MathTool.RadToDeg(ap.elevator[0, lr].delta), 1), xx, y);
                    y += 12;
                }

            }

            //g.SetFont(new Font("Sansserif", 11));
            y = 150;
            int dy = 9;
            xx = 2;
            int i;
            for (i = 0; i < ap.n_wing; i++)
            {
                for (lr = 0; lr < ap.wing[i].n_lr; lr++)
                {
                    for (int j = 0; j < ap.wing[i].n_wing_block; j++)
                    {
                        String str = "W" + j + AirPlane.lrName[lr] + ": " + DispFormat.DoubleFormat(ap.wing[i].wp[j, lr].k_stall, 4);
                        //          g.DrawString(str, xx, y);
                        y += dy;
                    }
                }
            }
            y += 3;
            for (i = 0; i < ap.n_htail; i++)
            {
                for (lr = 0; lr < ap.htail[i].n_lr; lr++)
                {
                    for (int j_0 = 0; j_0 < ap.htail[i].n_wing_block; j_0++)
                    {
                        String str_1 = "H" + j_0 + AirPlane.lrName[lr] + ": " + DispFormat.DoubleFormat(ap.htail[i].wp[j_0, lr].k_stall, 4);
                        // g.DrawString(str_1, xx, y);
                        y += dy;
                    }
                }
            }
            y += 3;
            for (i = 0; i < ap.n_vtail; i++)
            {
                for (lr = 0; lr < ap.vtail[i].n_lr; lr++)
                {
                    for (int j_2 = 0; j_2 < ap.vtail[i].n_wing_block; j_2++)
                    {
                        String str_3 = "V" + j_2 + AirPlane.lrName[lr] + ": " + DispFormat.DoubleFormat(ap.vtail[i].wp[j_2, lr].k_stall, 4);
                        // g.DrawString(str_3, xx, y);
                        y += dy;
                    }
                }
            }
            y += 3;
            for (i = 0; i < ap.n_elevator; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.elevator[i, lr].type != 0)
                    {
                        String str_4 = "E" + i + AirPlane.lrName[lr] + ": " + DispFormat.DoubleFormat(ap.elevator[i, lr].baseWingBlock.k_stall, 4);
                        // g.DrawString(str_4, xx, y);
                        y += dy;
                    }
                }
            }
            y += 3;
            for (i = 0; i < ap.n_aileron; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.aileron[i, lr].type != 0)
                    {
                        String str_5 = "A" + i + AirPlane.lrName[lr] + ": " + DispFormat.DoubleFormat(ap.aileron[i, lr].baseWingBlock.k_stall, 4);
                        // g.DrawString(str_5, xx, y);
                        y += dy;
                    }
                }
            }
            y += 3;
            for (i = 0; i < ap.n_rudder; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.rudder[i, lr].type != 0)
                    {
                        String str_6 = "R" + i + AirPlane.lrName[lr] + ": " + DispFormat.DoubleFormat(ap.rudder[i, lr].baseWingBlock.k_stall, 4);
                        // g.DrawString(str_6, xx, y);
                        y += dy;
                    }

                }

            }

            //g.SetColor(Java.Awt.Color.green);
            //g.SetFont(new Font("Sansserif", 10));
            dr.DrawAxis(g, 2.0D);
            double scale = 1.0D / ap.inp.m;
            for (i = 0; i < ap.n_wing; i++)
            {
                for (lr = 0; lr < ap.wing[i].n_lr; lr++)
                {
                    for (int j_7 = 0; j_7 < ap.wing[i].n_wing_block; j_7++)
                    {
                        dr.DrawVector(g, ap.wing[i].wp[j_7, lr].ac, ap.wing[i].wp[j_7, lr].fv.SclProd(scale), "W" + j_7 + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_htail; i++)
            {
                for (lr = 0; lr < ap.htail[i].n_lr; lr++)
                {
                    for (int j_8 = 0; j_8 < ap.htail[i].n_wing_block; j_8++)
                    {
                        dr.DrawVector(g, ap.htail[i].wp[j_8, lr].ac, ap.htail[i].wp[j_8, lr].fv.SclProd(scale), "H" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_vtail; i++)
            {
                for (lr = 0; lr < ap.vtail[i].n_lr; lr++)
                {
                    for (int j_9 = 0; j_9 < ap.vtail[i].n_wing_block; j_9++)
                    {
                        dr.DrawVector(g, ap.vtail[i].wp[j_9, lr].ac, ap.vtail[i].wp[j_9, lr].fv.SclProd(scale), "V" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_elevator; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.elevator[i, lr].type != 0)
                    {
                        dr.DrawVector(g, ap.elevator[i, lr].baseWingBlock.ac, ap.elevator[i, lr].d_fv.SclProd(scale), "E" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_aileron; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.aileron[i, lr].type != 0)
                    {
                        dr.DrawVector(g, ap.aileron[i, lr].baseWingBlock.ac, ap.aileron[i, lr].d_fv.SclProd(scale), "A" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_rudder; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.rudder[i, lr].type != 0)
                    {
                        dr.DrawVector(g, ap.rudder[i, lr].baseWingBlock.ac, ap.rudder[i, lr].d_fv.SclProd(scale), "R" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_t_flap; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.t_flap[i, lr].type != 0)
                    {
                        dr.DrawVector(g, ap.t_flap[i, lr].baseWingBlock.ac, ap.t_flap[i, lr].d_fv.SclProd(scale), "F" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_fuselage; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.fuslage[i, lr].flag != 0)
                    {
                        dr.DrawVector(g, ap.fuslage[i, lr].ac, ap.fuslage[i, lr].fv.SclProd(scale), "F" + i + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_LandingGear; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.landing_gear[i, lr].flag == 0)
                        continue;
                    dr.DrawVector(g, ap.landing_gear[i, lr].pg, ap.landing_gear[i, lr].n_fv.SclProd(scale), "G" + i + AirPlane.lrName[lr]);

                    dr.DrawVector(g, ap.landing_gear[i, lr].pg, ap.landing_gear[i, lr].f_fv.SclProd(scale), "");

                    dr.DrawVector(g, ap.landing_gear[i, lr].pa, ap.landing_gear[i, lr].a_fv.SclProd(scale), "G" + i + AirPlane.lrName[lr]);
                }
            }

            for (i = 0; i < ap.n_powerPlant; i++)
            {
                dr.DrawVector(g, ap.powerPlant[i].engine.GetPos(), ap.t_force.SclProd(scale), "E" + i);
                // g.SetColor(Java.Awt.Color.blue);
                if (ap.powerPlant[i].engine_type == 1)
                {
                    dr.DrawVector(g, ((ReciprocatingEngine)ap.powerPlant[i].engine).ac, ((ReciprocatingEngine)ap.powerPlant[i].engine).wash_direction.SclProd(-5.0D), "WASH" + i);
                }

            }

            //g.SetColor(Color.Yellow);
            //g.SetFont(new Font("Sansserif", 10));
            dr.DrawAxis(g, 2.0D);
            for (i = 0; i < ap.n_wing; i++)
            {
                for (lr = 0; lr < ap.wing[i].n_lr; lr++)
                {
                    for (int j_10 = 0; j_10 < ap.wing[i].n_wing_block; j_10++)
                    {
                        dr.DrawVector(g, ap.wing[i].wp[j_10, lr].ac, ap.wing[i].wp[j_10, lr].vd.SclProd(0.03D), "W" + j_10 + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_htail; i++)
            {
                for (lr = 0; lr < ap.htail[i].n_lr; lr++)
                {
                    for (int j_11 = 0; j_11 < ap.htail[i].n_wing_block; j_11++)
                    {
                        dr.DrawVector(g, ap.htail[i].wp[j_11, lr].ac, ap.htail[i].wp[j_11, lr].vd.SclProd(0.03D), "H" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_vtail; i++)
            {
                for (lr = 0; lr < ap.vtail[i].n_lr; lr++)
                {
                    for (int j_12 = 0; j_12 < ap.vtail[i].n_wing_block; j_12++)
                    {
                        dr.DrawVector(g, ap.vtail[i].wp[j_12, lr].ac, ap.vtail[i].wp[j_12, lr].vd.SclProd(0.03D), "V" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_elevator; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.elevator[i, lr].type != 0)
                    {
                        dr.DrawVector(g, ap.elevator[i, lr].baseWingBlock.ac, ap.elevator[i, lr].baseWingBlock.vd.SclProd(0.03D), "E" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_aileron; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.aileron[i, lr].type != 0)
                    {
                        dr.DrawVector(g, ap.aileron[i, lr].baseWingBlock.ac, ap.aileron[i, lr].baseWingBlock.vd.SclProd(0.03D), "A" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_rudder; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    if (ap.rudder[i, lr].type != 0)
                    {
                        dr.DrawVector(g, ap.rudder[i, lr].baseWingBlock.ac, ap.rudder[i, lr].baseWingBlock.vd.SclProd(0.03D), "R" + AirPlane.lrName[lr]);
                    }
                }
            }
            for (i = 0; i < ap.n_fuselage; i++)
            {
                for (lr = 0; lr <= 1; lr++)
                {
                    dr.DrawVector(g, ap.fuslage[i, lr].ac, ap.fuslage[i, lr].vd.SclProd(0.03D), "FUS" + i + AirPlane.lrName[lr]);
                }

            }

            // g.SetColor(Java.Awt.Color.black);

            // g.DrawString("TIRE M: " + PrintVal(ap.landing_gear[0, 0].tire.muX) + "/" + PrintVal(ap.landing_gear[0, 0].tire.muY), 150, 312);
            // g.DrawString("TIRE F': " + PrintVal(ap.landing_gear[0, 0].f_fv.x) + "/" + PrintVal(ap.landing_gear[0, 0].f_fv.y) + "/" + PrintVal(ap.landing_gear[0][0].f_fv.z), 150, 324);
            // g.DrawString("FLAG LAND': " + ap.flag_land, 150, 336);

            //  g.SetColor(Color.Red);
            if (ap.n_htail > 0)
            {
                for (lr = 0; lr < ap.htail[0].n_lr; lr++)
                {
                    dr.DrawVector(g, ap.htail[0].wp[0, lr].ac, ap.interference.htail_dv[lr].SclProd(-0.03D), "IH" + i + AirPlane.lrName[lr]);
                }
            }
            if (ap.n_vtail > 0)
            {
                for (lr = 0; lr < ap.vtail[0].n_lr; lr++)
                {
                    dr.DrawVector(g, ap.vtail[0].wp[0, lr].ac, ap.interference.vtail_dv[lr].SclProd(-0.03D), "IV" + i + AirPlane.lrName[lr]);
                }
            }
            for (i = 0; i < ap.n_fuselage; i++)
                for (lr = 0; lr <= 1; lr++)
                    if (ap.fuslage[i, lr].flag != 0)
                        dr.DrawVector(g, ap.fuslage[i, lr].ac, ap.interference.fuselage_dv[i, lr].SclProd(-0.03D), "IF" + i + AirPlane.lrName[lr]);
        }

        private String PrintVal(double x)
        {
            return DispFormat.DoubleFormat(x, 5, 3);
        }

        private String PrintDeg(double x)
        {
            return DispFormat.DoubleFormat(MathTool.RadToDeg(x), 3);
        }

        public void DrawSimInterfase(Graphics g, SimulatorInterface simif)
        {
            //  g.SetFont(bigFont);
            //  g.SetColor(simInterfaceColor);
            if (simif.pause_sw == 1)
            {
                //  g.DrawString("PAUSE", pause_x, pause_y);
            }
            // if (simif.slow_mode == 1)
            //g.DrawString("SLOW MOTION", slowMoton_x, slowMoton_y);
        }
    }
}