// FrontEnd Plus GUI for JAD
// DeCompiled : TimeParam.class

// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace FlightSimulator
{

    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class TimeParam
    {

        public double dt;
        public int t_disp;
        public int t_record;
        public double simT;
        public long tStart;
        public double tsim_dt;
        public int rec_counter;

        public TimeParam()
        {
            dt = 0.005D;
            t_disp = 6;
            t_record = 40;
            simT = 0.0D;
            tsim_dt = 0.0D;
            rec_counter = 0;
        }

        public void SetTSTART()
        {
            tStart = ((DateTime.Now).Ticks / 10000);
        }

        public long ThreadPeriodMsec()
        {
            return (long)(dt * 1000D) * (long)t_disp;
        }

        public double ThreadPeriod()
        {
            return dt * (double)t_disp;
        }
    }
}