// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Fsim
{

    using Jp.Maker1.Sim.Tools;
    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class TireMu
    {
        private static double[] beta = { 0, 0.0174532925199433D,
				0.03490658503988659D, 0.06981317007977318D, 0.1396263401595464D,
				0.2094395102393195D, 0.349065850398866D, 0.5235987755982988D,
				0.8726646259971648D, 1.221730476396031D, 1.570796326794897D };

        private static double[] mux_slip_beta00 = { 0, 0.02D, 0.03D, 0.05D,
				0.07000000000000001D, 0.09D, 0.12D, 0.17D, 1.0D };
        private static double[] mux_fmux_beta00 = { 0, 0.45D, 0.69D, 0.85D,
				0.9300000000000001D, 0.98D, 1.0D, 1.0D, 0.67D };
        private static double[] mux_slip_beta01 = { 0, 0.02D, 0.03D, 0.05D,
				0.07000000000000001D, 0.09D, 0.12D, 0.17D, 1.0D };
        private static double[] mux_fmux_beta01 = { 0, 0.45D, 0.69D, 0.85D,
				0.9300000000000001D, 0.98D, 1.0D, 1.0D, 0.67D };
        private static double[] mux_slip_beta02 = { 0, 0.02D, 0.04D, 0.06D, 0.08D,
				0.1D, 0.13D, 0.21D, 1.0D };
        private static double[] mux_fmux_beta02 = { 0, 0.45D, 0.7D, 0.85D, 0.92D,
				0.96D, 0.975D, 0.975D, 0.67D };
        private static double[] mux_slip_beta04 = { 0, 0.03D, 0.06D, 0.08D, 0.12D,
				0.16D, 0.22D, 0.32D, 0.45D, 1.0D };
        private static double[] mux_fmux_beta04 = { 0, 0.4D, 0.65D, 0.77D, 0.89D,
				0.92D, 0.92D, 0.91D, 0.88D, 0.665D };
        private static double[] mux_slip_beta08 = { 0, 0.05D, 0.08D, 0.12D, 0.16D,
				0.23D, 0.32D, 0.46D, 0.69D, 1.0D };
        private static double[] mux_fmux_beta08 = { 0, 0.35D, 0.52D, 0.65D, 0.74D,
				0.8100000000000001D, 0.85D, 0.84D, 0.78D, 0.66D };
        private static double[] mux_slip_beta12 = { 0, 0.07000000000000001D, 0.1D,
				0.16D, 0.2D, 0.26D, 0.36D, 0.42D, 0.51D, 0.87D, 1.0D };
        private static double[] mux_fmux_beta12 = { 0, 0.31D, 0.42D, 0.58D, 0.66D,
				0.73D, 0.78D, 0.79D, 0.79D, 0.7D, 0.65D };
        private static double[] mux_slip_beta20 = { 0, 0.1D, 0.2D, 0.27D, 0.33D,
				0.42D, 0.55D, 0.6800000000000001D, 0.8100000000000001D, 1.0D };
        private static double[] mux_fmux_beta20 = { 0, 0.25D, 0.44D, 0.54D, 0.6D,
				0.66D, 0.69D, 0.69D, 0.67D, 0.63D };
        private static double[] mux_slip_beta30 = { 0, 0.13D, 0.29D, 0.4D, 0.49D,
				0.58D, 0.74D, 0.9D, 1.0D };
        private static double[] mux_fmux_beta30 = { 0, 0.2D, 0.39D, 0.48D, 0.53D,
				0.5600000000000001D, 0.59D, 0.59D, 0.58D };
        private static double[] mux_slip_beta50 = { 0, 0.15D, 0.35D, 0.49D, 0.75D,
				1.0D };
        private static double[] mux_fmux_beta50 = { 0, 0.1D, 0.22D, 0.29D, 0.39D,
				0.43D };
        private static double[] mux_slip_beta70 = { 0, 0.17D, 0.37D, 1.0D };
        private static double[] mux_fmux_beta70 = { 0, 0.05D, 0.1D, 0.24D };
        private static double[] mux_slip_beta90 = { 0, 1.0D };
        private static double[] mux_fmux_beta90 = new double[2];

        private static Function2D[] fmux_beta = {
				new Function2D(mux_slip_beta00, mux_fmux_beta00),
				new Function2D(mux_slip_beta01, mux_fmux_beta01),
				new Function2D(mux_slip_beta02, mux_fmux_beta02),
				new Function2D(mux_slip_beta04, mux_fmux_beta04),
				new Function2D(mux_slip_beta08, mux_fmux_beta08),
				new Function2D(mux_slip_beta12, mux_fmux_beta12),
				new Function2D(mux_slip_beta20, mux_fmux_beta20),
				new Function2D(mux_slip_beta30, mux_fmux_beta30),
				new Function2D(mux_slip_beta50, mux_fmux_beta50),
				new Function2D(mux_slip_beta70, mux_fmux_beta70),
				new Function2D(mux_slip_beta90, mux_fmux_beta90) };

        private static Function3D fmux = new Function3D(beta, fmux_beta);

        private static double[] muy_slip_beta00 = { 0, 1.0D };
        private static double[] muy_fmuy_beta00 = new double[2];
        private static double[] muy_slip_beta01 = { 0, 0.02D, 0.04D, 0.13D, 0.24D,
				0.33D, 0.4D, 1.0D };
        private static double[] muy_fmuy_beta01 = { 0.25D, 0.26D, 0.26D, 0.15D,
				0.07000000000000001D, 0.05D, 0.04D, 0.02D };
        private static double[] muy_slip_beta02 = { 0, 0.01D, 0.03D, 0.11D, 0.17D,
				0.24D, 0.38D, 0.52D, 0.66D, 1.0D };
        private static double[] muy_fmuy_beta02 = { 0.49D, 0.5D, 0.5D, 0.3D, 0.21D,
				0.15D, 0.09D, 0.06D, 0.04D, 0.01D };
        private static double[] muy_slip_beta04 = { 0, 0.02D, 0.1D, 0.19D, 0.26D,
				0.37D, 0.52D, 0.75D, 1.0D };
        private static double[] muy_fmuy_beta04 = { 0.8100000000000001D,
				0.8100000000000001D, 0.54D, 0.35D, 0.26D, 0.18D, 0.12D, 0.08D,
				0.05D };
        private static double[] muy_slip_beta08 = { 0, 0.02D, 0.05D, 0.19D, 0.29D,
				0.43D, 0.59D, 0.79D, 1.0D };
        private static double[] muy_fmuy_beta08 = { 0.98D, 0.97D, 0.92D, 0.58D,
				0.41D, 0.29D, 0.2D, 0.13D, 0.09D };
        private static double[] muy_slip_beta12 = { 0, 0.01D, 0.04D, 0.06D, 0.15D,
				0.27D, 0.39D, 0.57D, 0.79D, 1.0D };
        private static double[] muy_fmuy_beta12 = { 1.0D, 1.0D, 0.99D, 0.95D,
				0.78D, 0.58D, 0.43D, 0.3D, 0.2D, 0.14D };
        private static double[] muy_slip_beta20 = { 0, 0.04D, 0.09D, 0.15D, 0.26D,
				0.43D, 0.55D, 0.79D, 1.0D };
        private static double[] muy_fmuy_beta20 = { 0.95D, 0.94D, 0.92D, 0.87D,
				0.75D, 0.5600000000000001D, 0.46D, 0.31D, 0.23D };
        private static double[] muy_slip_beta30 = { 0, 0.04D, 0.12D, 0.19D, 0.28D,
				0.5600000000000001D, 0.74D, 1.0D };
        private static double[] muy_fmuy_beta30 = { 0.9D, 0.89D, 0.87D, 0.84D,
				0.79D, 0.58D, 0.46D, 0.34D };
        private static double[] muy_slip_beta50 = { 0, 0.16D, 0.37D, 0.5D, 0.79D,
				1.0D };
        private static double[] muy_fmuy_beta50 = { 0.8100000000000001D, 0.8D,
				0.75D, 0.71D, 0.6D, 0.5D };
        private static double[] muy_slip_beta70 = { 0, 0.4D, 1.0D };
        private static double[] muy_fmuy_beta70 = { 0.73D, 0.71D, 0.62D };
        private static double[] muy_slip_beta90 = { 0, 1.0D };
        private static double[] muy_fmuy_beta90 = { 0.64D, 0.64D };

        private static Function2D[] fmuy_beta = {
				new Function2D(muy_slip_beta00, muy_fmuy_beta00),
				new Function2D(muy_slip_beta01, muy_fmuy_beta01),
				new Function2D(muy_slip_beta02, muy_fmuy_beta02),
				new Function2D(muy_slip_beta04, muy_fmuy_beta04),
				new Function2D(muy_slip_beta08, muy_fmuy_beta08),
				new Function2D(muy_slip_beta12, muy_fmuy_beta12),
				new Function2D(muy_slip_beta20, muy_fmuy_beta20),
				new Function2D(muy_slip_beta30, muy_fmuy_beta30),
				new Function2D(muy_slip_beta50, muy_fmuy_beta50),
				new Function2D(muy_slip_beta70, muy_fmuy_beta70),
				new Function2D(muy_slip_beta90, muy_fmuy_beta90) };

        private static Function3D fmuy = new Function3D(beta, fmuy_beta);

        public static double X(double s, double beta_0)
        {
            return fmux.F(s, beta_0);
        }

        public static double Y(double s, double beta_0)
        {
            return fmuy.F(s, beta_0);
        }
    }
}