// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Sim.Tools
{

    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class UnitConvert
    {
        public static double Ttok(double tc)
        {
            return tc + 273.14999999999998D;
        }

        public static double Ktot(double t)
        {
            return t - 273.14999999999998D;
        }

        public static double Mps2kmph(double v)
        {
            return v * 3.6D;
        }

        public static double Mps2kt(double v)
        {
            return v * 3.6D / 1.852D;
        }

        public static double Kmph2kmps(double v)
        {
            return v / 3.6D;
        }

        public static double Kt2mps(double v)
        {
            return v / 3.6D * 1.852D;
        }

        public static double M2ft(double x)
        {
            return x / 0.3048D;
        }

        public static double Hp2w(double x)
        {
            return x * 745.70000000000005D;
        }

        public static double W2hp(double x)
        {
            return x / 745.70000000000005D;
        }

        public static double Ps2w(double x)
        {
            return x * 735.5D;
        }

        public static double W2ps(double x)
        {
            return x / 735.5D;
        }
    }
}