// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Vsys3.Tools
{

    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class VsElementFactory
    {
        public static VsElement CreateElement(VsElement elem)
        {
            VsElement ret = null;
            String type = elem.ElemType();

            if (type.Equals("VsPoint"))
            {
                ret = new VsPoint((VsPoint)elem);
            }
            else if (type.Equals("VsPolygon"))
            {
                ret = new VsPolygon((VsPolygon)elem);
            }
            else if (type.Equals("VsPolygon2"))
            {
                ret = new VsPolygon2((VsPolygon2)elem);
            }
            else if (type.Equals("VsPolygon3"))
            {
                ret = new VsPolygon3((VsPolygon3)elem);
            }
            else if (type.Equals("VsPolygon4"))
            {
                ret = new VsPolygon4((VsPolygon4)elem);
            }
            else if (type.Equals("VsSegment"))
            {
                ret = new VsSegment((VsSegment)elem);
            }
            else if (type.Equals("VsString"))
            {
                ret = new VsString((VsString)elem);
            }
            else if (type.Equals("VsString2"))
            {
                ret = new VsString2((VsString2)elem);
            }
            else if (type.Equals("VsObject"))
            {
                ret = new VsObject((VsObject)elem);
            }

            return ret;
        }
    }
}