// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Vsys3.Tools
{


    using System;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class VsObjectList
    {
        public VsObjectList()
        {
            list = new Hashtable();
        }

        private Hashtable list;

        public void Add(String id, VsObject obj)
        {
            list.Add(id, obj);
            //ILOG.J2CsMapping.Collections.Collections.Put(list, id, obj);
        }

        public VsObject Get(String id)
        {
            return (VsObject)list[id];
        }

        public void Print()
        {
            int i = 1;
            System.Console.Out.WriteLine("VsObjectList ::");
            System.Console.Out.WriteLine("{");
            //for (Iterator ide = new ILOG.J2CsMapping.Collections.IteratorAdapter(list.Keys.GetEnumerator()); ide.HasNext(); )
            //{
            //    String id = (String)ide.Next();
            //    System.Console.Out.WriteLine("  " + Jp.Maker1.Util.DispFormat.Lpad(i++.ToString(), 3) + " " + id);
            //    System.Console.Out.Write("        ");
            //    Get(id).BoundingBox().Print();
            //}
            System.Console.Out.WriteLine("}");
        }
    }
}