// --------------------------------------------------------------------------------------------------
// This file was automatically generated by J2CS Translator (http://j2cstranslator.sourceforge.net/). 
// Version 1.3.6.20110331_01     
// 11/05/19 19:45    
// ${CustomMessageForDisclaimer}                                                                             
// --------------------------------------------------------------------------------------------------
namespace Jp.Maker1.Vsys3.Tools
{


    using System;
    using System.Drawing;
    using System.Collections;
    using System.ComponentModel;
    using System.IO;
    using System.Runtime.CompilerServices;

    public class VsPolygon4 : VsElement
    {
        public String type;
        public Material mate;
        public Material mateB;
        public Color col;
        public Polygon3D pol;
        internal bool faceflag;

        public VsPolygon4()
        {
            type = "VsPolygon4";
            col = Color.Black;
            faceflag = true;
            mate = new Material();
            mateB = new Material();
            pol = new Polygon3D();
            faceflag = pol.BackfaceCheck();
        }

        public VsPolygon4(int np, double[] x, double[] y, double[] z, Material material, Material materialB)
        {
            type = "VsPolygon4";
            col = Color.Black;
            faceflag = true;
            mate = material;
            mateB = materialB;
            pol = new Polygon3D(np, x, y, z);
            faceflag = pol.BackfaceCheck();
        }

        public VsPolygon4(Polygon3D p, Material material, Material materialB)
        {
            type = "VsPolygon4";
            col = Color.Black;
            faceflag = true;
            mate = material;
            mateB = materialB;
            pol = p;
            faceflag = pol.BackfaceCheck();
        }

        public VsPolygon4(VsPolygon4 p)
        {
            type = "VsPolygon4";
            col = Color.Black;
            faceflag = true;
            mate = new Material(p.mate);
            mateB = new Material(p.mateB);
            col = p.col;
            pol = new Polygon3D(p.pol);
            faceflag = p.faceflag;
        }

        public virtual String ElemType()
        {
            return type;
        }

        public virtual VsElement Clip2D(Clipper clip)
        {
            VsPolygon4 ret = new VsPolygon4(this);
            if (ret.pol.NVertex() >= 3)
            {
                ret.pol = clip.Vs_polygon_clip_2d(ret.pol);
            }
            return ret;
        }

        public virtual VsElement Clip3DF(Clipper clip)
        {
            VsPolygon4 ret = new VsPolygon4(this);
            if (ret.pol.NVertex() >= 3)
            {
                ret.pol = clip.Vs_polygon_clip_3df(ret.pol);
                ret.faceflag = ret.pol.BackfaceCheck();
            }
            return ret;
        }

        public virtual double Depth()
        {
            return pol.ZMax();
        }

        public virtual void Draw(Graphics g)
        {
            if (pol.NVertex() >= 3)
            {
                //g.SetColor(col);
                int[] ix = pol.IxArray();
                int[] iy = pol.IyArray();
                int n = ix.Length;
                //g.FillPolygon(ix, iy, n);
            }
        }

        public virtual void Complete_draw(Graphics g)
        {
            if (pol.NVertex() >= 3)
            {
                // g.SetColor(col);
                int[] ix = pol.IxArray();
                int[] iy = pol.IyArray();
                int n = ix.Length;
                //  g.FillPolygon(ix, iy, n);

                for (int i = 0; i < n; i++)
                {
                    int ie = i + 1;
                    if (ie >= n)
                        ie = 0;
                    // g.DrawLine(ix[i], iy[i], ix[ie], iy[ie]);
                }
            }
        }

        public void DrawWireframe(Graphics g)
        {
            if (pol.NVertex() >= 3)
            {
                // g.SetColor(Color.Black);
                int[] ix = pol.IxArray();
                int[] iy = pol.IyArray();
                int n = ix.Length;
                // g.DrawPolygon(ix, iy, n);
            }
        }

        public virtual void Print()
        {
            System.Console.Out.Write(type + "::");
            mate.Print();
            mateB.Print();
            System.Console.Out.Write("::");
            pol.Print();
            System.Console.Out.Write("NML:");
            pol.Nomal_vartex1().PrintVec();
            System.Console.Out.WriteLine();
        }

        public virtual VsElement Project(Projector proj)
        {
            VsPolygon4 ret = new VsPolygon4(this);
            if (ret.pol.NVertex() >= 3)
            {
                ret.pol = ret.pol.Project(proj);
            }
            return ret;
        }

        public virtual VsElement Transform(Matrix44 mat)
        {
            VsPolygon4 ret = new VsPolygon4(this);

            if (ret.pol.NVertex() >= 3)
            {
                ret.pol = ret.pol.Transform(mat);
                ret.faceflag = ret.pol.BackfaceCheck();
            }

            return ret;
        }

        public void SetColor(OpticalAmbience oa)
        {
            LightColor brightness = new LightColor(0.0D, 0.0D, 0.0D);
            if (pol.NVertex() >= 3)
            {
                Vector3D nml = pol.Nomal_vartex1();
                if (faceflag)
                    brightness = oa.Brightness(new Vector3D(0.0D, 0.0D, 0.0D), pol.GetVertex(1), nml, mate);
                else
                {
                    brightness = oa.Brightness(new Vector3D(0.0D, 0.0D, 0.0D), pol.GetVertex(1), nml.SclProd(-1.0D), mateB);
                }
            }
            col = brightness.GetColor();
        }

        public virtual BoundingBox BoundingBox()
        {
            return pol.BoundingBox();
        }

        public virtual void SetColor(Color colIn)
        {
        }

        public virtual void SetMaterial(Material mate_0)
        {
            mate = new Material(mate_0);
            mateB = new Material(mate_0);
        }
    }
}